export const LOGOUT_USER = "LOGOUT_USER";

export const SET_LIST_TYPE = "SET_LIST_TYPE";

export const STARSHIPS_LOADING = "STARSHIPS_LOADING";
export const STARSHIPS_LOAD_SUCCESS = "STARSHIPS_LOAD_SUCCESS";
export const STARSHIPS_LOAD_ERROR = "STARSHIPS_LOAD_ERROR";
